apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-lego
  namespace: kube-lego
data:
  # modify this to specify your address
  lego.email: "test@gmail.com"
  # configure letsencrypt's production api
  lego.url: "https://acme-v01.api.letsencrypt.org/directory"
  # For testing, use their testing API if you wish
  # (generates non browser certs, no API rate limiting)
  # lego.url: "https://acme-staging.api.letsencrypt.org/directory"
